config/routes.rb
Rails.application.routes.draw do
    devise_for :users, path_names: { sign_up: '' }, controllers: { sessions: 'sessions' }

    resources :users_admin, controller: 'users'

    root 'welcome#index'
    # mailbox folder routes
    get 'mailbox/inbox', to:  'mailbox#inbox', as: :mailbox_inbox
    get 'mailbox/sent', to: 'mailbox#sent', as: :mailbox_sent
    get 'mailbox/trash', to: 'mailbox#trash', as: :mailbox_trash

    resources :conversations do
        member do
            post :reply
            post :trash
            post :untrash
        end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

    #Validation for avatar
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

    #Setting for mailboxer
    acts_as_messageable

    def mailboxer_name
      self.name
    end

    def mailboxer_email(object)
      self.email
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    helper_method :mailbox, :conversation

    private

    def mailbox
       @mailbox ||= current_user.mailbox
    end

    def conversation
       @conversation ||= mailbox.conversations.find(params[:id])
    end

    protected

    def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
       devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])

    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

  def reply
     current_user.reply_to_conversation(conversation, message_params[:body])
     flash[:notice] = "Your reply message was successfully sent!"
     redirect_to conversation_path(conversation)
  end

  def trash
   conversation.move_to_trash(current_user)
   redirect_to mailbox_inbox_path
  end

  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body, :recipients)
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end
end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
    before_action :authenticate_user!

    def inbox
        @inbox = mailbox.inbox
        @active = :inbox
    end

    def sent
        @sent = mailbox.sentbox
        @active = :sent
    end

    def trash
        @trash = mailbox.trash
        @active = :trash
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    include MailboxHelper

    # POST /resource/sign_in
    def create
        self.resource = warden.authenticate!(auth_options)
        if unread_messages_count > 0
            flash[:success] = "Signed in successfully. You have #{view_context.link_to("#{unread_messages_count} unread massage inbox.", mailbox_inbox_path)}"
        else
            flash[:success] = "Signed in successfully. You don't have any unread message."
        end
        sign_in(resource_name, resource)
        yield resource if block_given?
        respond_with resource, location: after_sign_in_path_for(resource)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :signed_in_user
    before_action :authenticate_user!, :redirect_unless_admin, only: [:index, :show, :new, :create, :edit, :update, :destroy]

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = 'You create new user!'
            redirect_to users_admin_index_path
        else
            flash[:error] = 'please complete all fields'
            render 'new'
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            flash[:success] = 'Profile updated'
            redirect_to users_admin_path
        else
            flash[:error] = 'Please complete all fields'
            render 'edit'
        end
    end

    def destroy
        User.find(params[:id]).destroy
        flash[:success] = 'User deleted.'
        redirect_to users_admin_index_url
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password,
                                     :password_confirmation, :avatar)
    end

    def signed_in_user
        unless signed_in?
            flash[:error] = 'Please sign in.'
            redirect_to user_session_path
        end
    end

    def redirect_unless_admin
        unless current_user.admin?
            flash[:error] = 'Only admins can do that'
            redirect_to root_path
        end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
     case level.to_sym
     when :notice then "alert alert-info"
     when :success then "alert alert-success"
     when :error then "alert  alert-danger"
     when :alert then "alert alert-warning"
     end
  end

  def active_page(active_page)
    @active == active_page ? "active" : ""
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
    def unread_messages_count
        current_user.mailbox.inbox(read: false).count
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <%= image_tag conversation.originator.avatar.url(:thumb)%>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <% if current_page?(mailbox_inbox_path) or current_page?(mailbox_trash_path) %>
      <small><b>From User: </b></small><%= conversation.originator.name %> <br>
      <% else %>
      <small><b>To User: </b></small><%=  conversation.participants.find { |p| p != current_user }.name %> <br>
      <% end %>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small><br>
      <small><b>Text: </b> <%= truncate conversation.messages.last.body, length: 50 %></small>
    </h4>
    <%= link_to "Read massege", conversation_path(conversation), class: "btn btn-success btn-sm"  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
<div class="form-group">
    <%= f.label :recipients %>
    <%= f.collection_select(:recipients, User.where.not(id: current_user.id), :id, :name, {prompt: "Select a recipient"}, {class: "form-control"}) %>
</div>
<div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :message %>
    <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 5  %>
</div>

<%= f.submit "Send Message", class: "btn btn-success" %>
<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
  <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <%= image_tag message.sender.avatar.url(:thumb), class:"rounded"%>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <% if message.sender != conversation.originator %>
          <small><b>Answer from: </b></small><%= message.sender.name %> <br>
          <% else %>
          <small><b>From: </b></small><%= message.sender.name %> <br>
          <% end %>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
      </div>
    </div>
    <div class="panel panel-default classWithPad">
      <div class="panel-heading">
        <b>Text: </b><%= message.body %>
      </div>
    </div>
  <hr>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-6">
    <%= link_to "New message", new_conversation_path, class: "btn btn-success classWithPad" %>
  </div>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
    <% else %>
        <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger classWithPad', method: :post,
                    data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_flash_messages.html.erb
<div>
    <% flash.each do |name, msg| %>
    <div class="alert alert-dismissable <%= flash_class(name) %> fade in">
        <a class="close" data-dismiss="alert">&#215</a>
        <% if msg.is_a?(String) %>
        <div id="flash_<%= name %>">
            <%= sanitize(msg) %>
        </div>
        <% end %>
    </div>
    <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-custom navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "MessengerApp", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <%= image_tag current_user.avatar.url(:thumb), class: "round-image-30" %>
                        <%= "Hello, #{current_user.name}" %>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Edit profile", edit_user_registration_path(current_user) %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                    </ul>
                </li>
                    <% if current_user.admin? %>
                <li><%= link_to "Users", users_admin_index_path %></li>
                <% end %>
                <li><%= link_to "Message", mailbox_inbox_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
                <li class="active"><%= link_to "Login", new_user_session_path %></li>
                <li><%= link_to "Home", root_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>MessengerAppTickets</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= render 'layouts/nav' %>
        <%= render 'layouts/flash_messages' %>

        <div class="container">
            <%= yield %>
        </div>

        <footer class="navbar-fixed-bottom">
            <div class="container text-center">
                &copy; <%= Date.today.year %> Andrian Hretsko <a href="https://tickets.ua/"> for Tickets.ua</a>
            </div>
        </footer>
    </body>
</html>

app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
    <li class="<%= active_page(:inbox) %>">
        <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%= unread_messages_count%></span>
        <span class="glyphicon glyphicon-envelope"></span>
        <span>Inbox</span>
        <% end %>
    </li>
    <li class="<%= active_page(:sent) %>">
        <%= link_to mailbox_sent_path do %>
        <span class="glyphicon glyphicon-open-file"></span>
        <span>Sent</span>
        <% end %>
    </li>

    <li class="<%= active_page(:trash) %>">
        <%= link_to mailbox_trash_path do %>
        <span class="glyphicon glyphicon-trash"></span>
        <span>Trash</span>
        <% end %>
    </li>
</ul>

app/views/mailbox/_view.html.erb
<div class="row">

    <div class="col-md-12">
        <%= link_to "New message", new_conversation_path, class: "btn btn-success classWithPad" %>
        <% if current_page?(mailbox_inbox_path) %>
            <%= link_to 'Refresh inbox', 'javascript:refresh()', class: "btn btn-primary classWithPad" %>
        <% end %>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-body">
                <%= render 'mailbox/folders' %>
            </div>
        </div>
    </div>

    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-body">
                <% if is_conversation %>
                <%= render 'conversations/form' %>
            <% else %>
                <%= render partial: 'conversations/conversation', collection: messages %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/mailbox/folders.html.erb
<ul class="nav nav-pills nav-stacked">
    <li class="<%= active_page(:inbox) %>">
        <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span>Inbox</span>
        <% end %>
    </li>
    <li class="<%= active_page(:sent) %>">
        <%= link_to mailbox_sent_path do %>

        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span>Sent</span>
        <% end %>
    </li>

    <li class="<%= active_page(:trash) %>">
        <%= link_to mailbox_trash_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span>Trash</span>
        <% end %>
    </li>
</ul>

app/views/mailbox/inbox.html.erb
<div class="dynamic">
    <%= render partial: 'mailbox/view', locals: { is_conversation: false, messages: @inbox } %>
<div>

app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/view', locals: { is_conversation: false, messages: @sent } %>

app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/view', locals: { is_conversation: false, messages: @trash } %>

app/views/users/edit.html.erb
<h1>Update user profile</h1>

<div class="panel panel-default">
    <div class="panel-heading">
        <%= form_for @user, url: users_admin_path(@user) do |f| %>

        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
            <div style="width: 150px;">
                <%= f.label :avatar %>
                <%= image_tag @user.avatar.url(:thumb), class: "img-thumbnail rounded float-left" %>
                <%= f.file_field :avatar, label: "Choose avatar" %>

            </div>
        </div>

        <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, :autocomplete => "off", class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation %><br/>
            <%= f.password_field :password_confirmation, class: "form-control"  %>
        </div>

        <%= f.submit "Save changes", class: "btn btn-large btn-success" %>
        <%= link_to 'Back', users_admin_index_path, class:"btn btn-primary" %>
        <% end %>

    </div>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= link_to 'Add new user', new_users_admin_path, method: :get, class: "btn btn-success classWithPad" %>

<ul class="list-group">
    <% @users.each do |user| %>
    <li class="list-group-item">
        <%= image_tag user.avatar.url(:thumb), class: "img-thumbnail" %>
        <%= user.name %>

        <div class="pull-right">
            <%= link_to "About user", users_admin_path(user.id), class: "btn btn-sm btn-info" %>
            <%= link_to "Edit profile", edit_users_admin_path(user.id), class: "btn btn-sm btn-warning"%>
            <% if !user.admin %>
            <%= link_to "Delete", users_admin_path(user.id), method: :delete,
                                 data: { confirm: "You sure?" }, class: "btn btn-sm btn-danger" %>
            <% end %>
        </div>

    </li>
    <% end %>
</ul>

app/views/users/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>NEW USER</h4>
  </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <h3>Information about user</h3>
      <hr />
      <h1>
        <%= image_tag @user.avatar.url(:medium), class:"img-thumbnail"%>
        <%= @user.name %>
      </h1>
      <p>Email: <%= @user.email %></p>
    </section>

    <%= link_to 'Back', users_admin_index_path, class:"btn btn-primary" %>

  </aside>
</div>

app/views/welcome/index.html.erb
<div class="text-center jumbotron">
    <h1>Welcome to the Messenger App</h1>
    <p><%= image_tag("index.jpeg", alt: "Message", class:"img-thumbnail") %></p>
    <% if user_signed_in? %>
    <%= link_to 'Your messages', mailbox_inbox_path, class: "btn btn-success btn-lg" %>
      <% if current_user.admin? %>
        <%= link_to "Manage user accounts", users_admin_index_path, class: "btn btn-primary btn-lg" %>
      <% end %>
    <% else %>
    <%= link_to "Log in now!", new_user_session_path, class: "btn btn-primary btn-lg" %>
    <% end %>
</div>